Activiti/activiti-examples

spring-boot-sample-activiti/src/main/java/org/activiti/Application.java, spring-boot-sample-activiti/src/main/resources/application.properties
@erdemedeiros @ryandawsonuk please review and merge
=> enabling auto discovery

spring-boot-sample-activiti/README.md, spring-boot-sample-activiti/docker-compose.yml, spring-boot-sample-activiti/src/main/resources/application.properties
Example updates that follow https://github.com/Activiti/Activiti/pull/1360
=> zuul and eureka in docker-compose 1339

spring-boot-sample-activiti/docker-compose.yml, spring-boot-sample-activiti/pom.xml, spring-boot-sample-activiti/src/main/resources/application.properties
For https://github.com/Activiti/Activiti/issues/1368
Have verified that it's using postgres by querying the DB directly using dbVisualizer on jdbc:postgresql://localhost:5432/mydb
=> switch sample app to postgres

spring-boot-sample-activiti/pom.xml
Reduces size of image from approx 700mb to approx 170mb
=> smaller docker images

spring-boot-sample-activiti/README.md
These three PRs all linked:
https://github.com/Activiti/activiti-examples/pull/8
https://github.com/Activiti/activiti-spring-boot-starters/pull/1
https://github.com/Activiti/Activiti/pull/1385
=> update as starters moved

spring-boot-sample-activiti/src/main/java/org/activiti/Application.java
@ryandawsonuk can you please check and merge this one
=> using new @ActivitiRuntimeBundle for app config

loan-request/pom.xml, loan-request/src/main/resources/org/activiti/spring/loanrequest/LoanRequest-context.xml
=> Fix dbcp dependency

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed version changes from the source code in repository: `Activiti/activiti-dependencies` ref: `master`
=> update Activiti/activiti-dependencies to master

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.28`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.34

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.35`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.38

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.39`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.42

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.43`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.56

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.57`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.65

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.68`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.69

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.70`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.70

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.71`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.71

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.72`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.72

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.74`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.74

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.75`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.75

activiti-api-basic-full-example/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.76`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.76

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.77`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.77

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.78`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.78

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.79`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.79

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.80`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.80

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.81`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.81

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.82`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.82

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.87`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.87

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.89`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.89

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.90`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.90

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.91`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.94

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.95`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.95

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.96`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.96

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/DemoApplication.java, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-full-example-nobean/src/main/java/org/activiti/examples/DemoApplication.java, activiti-api-basic-process-example/pom.xml, activiti-api-basic-process-example/src/main/java/org/activiti/examples/DemoApplication.java, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-spring-integration-example/src/main/java/org/activiti/examples/DemoApplication.java, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.97`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.97

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.98`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.98

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.99`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.99

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.100`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.100

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.101`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.101

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.102`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.102

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.103`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.103

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.104`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.104

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.105`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.105

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.1`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.1

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.2`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.2

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.3`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.3

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.106`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.106

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.4`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.4

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.5`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.5

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.6`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.6

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.7`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.7

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.107`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.107

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.8`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.8

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.108`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.108

activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.0.109`
=> update org.activiti.dependencies:activiti-dependencies to 7.0.109

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.9`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.9

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.10`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.10

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.11`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.11

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.12`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.12

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.13`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.13

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.14`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.14

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.15`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.15

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-connector-example/src/main/java/org/activiti/examples/DemoApplication.java, activiti-api-basic-connector-example/src/main/resources/processes/RankMovie.bpmn20.xml, activiti-api-basic-connector-example/src/main/resources/processes/RankMovieWithUUIDs.bpmn20.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
Related to https://github.com/Activiti/Activiti/issues/2589
Depends on https://github.com/Activiti/Activiti/pull/2671
=> Use connectorName.actionName to match connector implementation

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.18`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.18

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.19`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.19

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.20`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.20

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.21`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.21

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.22`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.22

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.23`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.23

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.24`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.24

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.25`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.25

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.26`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.26

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.27`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.27

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-connector-example/src/main/resources/processes/RankMovie-extensions.json, activiti-api-basic-connector-example/src/main/resources/processes/RankMovieWithUUIDs-extensions.json, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
Related to https://github.com/Activiti/Activiti/issues/2529
Depends on https://github.com/Activiti/Activiti/pull/2783
=> Deal with names vs UUIDs in connectors and variable mappings

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.29`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.29

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.30`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.30

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.31`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.31

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.32`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.32

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.33`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.33

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.34`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.34

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.35`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.35

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.36`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.36

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.37`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.37

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.38`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.38

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.39`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.39

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.40`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.40

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.41`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.41

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.42`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.42

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.43`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.43

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.44`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.44

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.45`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.45

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.46`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.46

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.47`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.47

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.48`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.48

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.49`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.49

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.50`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.50

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.51`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.51

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.52`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.52

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.53`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.53

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.54`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.54

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.55`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.55

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.56`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.56

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.57`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.57

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.58`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.58

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.59`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.59

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.60`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.60

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.61`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.61

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
Ref https://github.com/Activiti/Activiti/issues/2616
=> [Activiti-3093] Update Spring Boot to version 2.1.6.RELEASE

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.63`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.63

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.65`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.65

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.66`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.66

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.67`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.67

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.68`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.68

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.69`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.69

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.70`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.70

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.71`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.71

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.72`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.72

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.73`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.73

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.74`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.74

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.75`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.75

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.76`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.77

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.78`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.78

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.79`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.79

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.80`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.80

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.81`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.81

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.82`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.82

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.83`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.83

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.84`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.84

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.85`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.85

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.86`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.86

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.87`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.87

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.88`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.88

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.89`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.89

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.90`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.90

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.91`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.101

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.102`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.102

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.103`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.103

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.104`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.104

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.105`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.105

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.106`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.106

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.107`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.107

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.108`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.108

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.109`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.109

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.110`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.110

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.111`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.111

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.112`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.112

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.113`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.113

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.114`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.114

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.115`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.115

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.116`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.116

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.117`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.117

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.118`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.118

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.119`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.119

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.120`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.120

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.121`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.121

activiti-api-basic-connector-example/pom.xml, activiti-api-basic-full-example-bean/pom.xml, activiti-api-basic-full-example-nobean/pom.xml, activiti-api-basic-process-example/pom.xml, activiti-api-basic-task-example/pom.xml, activiti-api-spring-integration-example/pom.xml, activiti-api-web-example/pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.dependencies:activiti-dependencies` to: `7.1.122`
=> update org.activiti.dependencies:activiti-dependencies to 7.1.122
